# Generated by Django 3.0.8 on 2020-12-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=70)),
                ('course_price', models.IntegerField()),
                ('paid_price', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('enrollment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Enrollment')),
            ],
        ),
    ]
