# Generated by Django 3.0.8 on 2020-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='course_price',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='paid_price',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reference',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_retreival_reference_no',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
