# Generated by Django 3.0.8 on 2020-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201210_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_retreival_reference_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
