# Generated by Django 3.0.8 on 2020-12-10 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='trial',
        ),
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='expiries_at',
            field=models.DateTimeField(default=main.models.Enrollment.set_expiery),
        ),
        migrations.AlterField(
            model_name='trial',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trial', to=settings.AUTH_USER_MODEL),
        ),
    ]
