# Generated by Django 3.0.8 on 2020-12-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201211_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='course',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
