# Generated by Django 3.0.8 on 2020-12-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201211_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='completed',
        ),
    ]
